#!/usr/bin/env python3
"""Convert pages/**/*.ipynb into Jekyll-ready Markdown pages.

Run locally via build.command, or in CI before `jekyll build`. Notebooks are
expected to already have their outputs saved (no re-execution happens here).
"""

import json
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote

import yaml

REPO_URL = "https://github.com/beauchamplab/LabWiki"
AUTOGEN_MARKER = "<!-- AUTO-GENERATED from {stem}.ipynb by scripts/convert_notebooks.py — DO NOT EDIT DIRECTLY -->"


def find_notebooks(pages_root: Path):
    for p in sorted(pages_root.rglob("*.ipynb")):
        if ".ipynb_checkpoints" not in p.parts:
            yield p


def read_front_matter(path: Path) -> dict:
    """Parse the YAML front matter block of a page, or {} if absent/malformed."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    match = re.match(r"^---\n(.*?)\n---\s*(?:\n|$)", text, re.DOTALL)
    if not match:
        return {}
    try:
        data = yaml.safe_load(match.group(1))
    except yaml.YAMLError:
        return {}
    return data if isinstance(data, dict) else {}


def resolve_nav(nb_path: Path, pages_root: Path):
    """Derive (parent, grand_parent) from the vault's own section pages.

    just-the-docs section landing pages are siblings of the directory they
    head: pages/Beauchamp/Data_Processing.md heads Data_Processing/. Walk up
    from the notebook's directory to the nearest ancestor whose landing page
    declares has_children (a page without it is a leaf, not a section, and
    cannot be a parent). A notebook then sits under that section, so it
    inherits the section's own parent as its grand_parent.
    """
    directory = nb_path.parent
    while directory != pages_root.parent:
        section = directory.parent / f"{directory.name}.md"
        front_matter = read_front_matter(section)
        if front_matter.get("has_children") and front_matter.get("title"):
            return (front_matter["title"], front_matter.get("parent"))
        directory = directory.parent
    return (None, None)


def extract_title(nb_json, fallback_stem):
    for cell in nb_json.get("cells", []):
        if cell.get("cell_type") == "markdown":
            text = "".join(cell.get("source", []))
            match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
            if match:
                return match.group(1).strip()
    return fallback_stem.replace("_", " ").replace("-", " ").title()


def convert_one(nb_path: Path, pages_root: Path, repo_root: Path):
    nb_json = json.loads(nb_path.read_text(encoding="utf-8"))
    jekyll_meta = nb_json.get("metadata", {}).get("jekyll", {})

    parent, grand_parent = resolve_nav(nb_path, pages_root)
    parent = jekyll_meta.get("parent", parent)
    grand_parent = jekyll_meta.get("grand_parent", grand_parent)
    title = jekyll_meta.get("title") or extract_title(nb_json, nb_path.stem)

    out_md = nb_path.with_suffix(".md")

    if out_md.exists():
        existing = out_md.read_text(encoding="utf-8")
        if "AUTO-GENERATED" not in existing:
            print(
                f"ERROR: {out_md} exists and was not generated by this script "
                "— refusing to overwrite.",
                file=sys.stderr,
            )
            sys.exit(1)

    subprocess.run(
        [
            sys.executable,
            "-m",
            "nbconvert",
            "--to",
            "markdown",
            "--output-dir",
            str(nb_path.parent),
            "--output",
            nb_path.stem,
            f"--NbConvertApp.output_files_dir={{notebook_name}}_nbconvert_artifacts",
            str(nb_path),
        ],
        check=True,
    )

    body = out_md.read_text(encoding="utf-8")

    front_matter = ["---", "layout: default", f'title: "{title}"']
    if parent:
        front_matter.append(f"parent: {parent}")
    if grand_parent:
        front_matter.append(f"grand_parent: {grand_parent}")
    if "author" in jekyll_meta:
        front_matter.append(f"author: {jekyll_meta['author']}")
    if "date_created" in jekyll_meta:
        front_matter.append(f"date_created: {jekyll_meta['date_created']}")
    front_matter.append("---")

    rel_path = quote(nb_path.relative_to(repo_root).as_posix(), safe="/")
    source_link = f"[View source notebook on GitHub]({REPO_URL}/blob/main/{rel_path})"

    header = AUTOGEN_MARKER.format(stem=nb_path.stem)
    out_md.write_text(
        "\n".join(front_matter) + "\n\n" + header + "\n\n" + source_link + "\n\n" + body,
        encoding="utf-8",
    )
    print(f"  converted: {nb_path.relative_to(repo_root)} -> {out_md.relative_to(repo_root)}")


def main():
    repo_root = Path(__file__).resolve().parent.parent
    pages_root = repo_root / "pages"
    notebooks = list(find_notebooks(pages_root))
    if not notebooks:
        print("No .ipynb files found under pages/ — nothing to do.")
        return
    print(f"Converting {len(notebooks)} notebook(s)...")
    for nb in notebooks:
        convert_one(nb, pages_root, repo_root)


if __name__ == "__main__":
    main()
